menu/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'menu'

urlpatterns = [
    path('', views.home, name='home'),
    path('last-week-menu', views.last_week_menu, name='last_week_menu'),
    path('page-in-progress', views.progress_page, name='progress_page'),
    path('weekly-menu/', views.weekly_menu, name='weekly_menu'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'), 
    path('save-user-choices', views.save_user_choices, name='save_user_choices'),
    
    path('update-weekly-menu', views.update_weekly_menu, name='update_weekly_menu'),
    
    path('reports/', views.reports_page, name='reports_page'),
    path('generate-full-report/', views.generate_full_report_button, name='generate_full_report_button'),
    path('generate-pdf-report-unity-one/', views.generate_pdf_report_unit_one, name='generate_pdf_report_unit_one'),
    path('generate-pdf-report-unity-two/', views.generate_pdf_report_unit_two, name='generate_pdf_report_unit_two'),
    path('generate-pdf-report-unity-five/', views.generate_pdf_report_unit_five, name='generate_pdf_report_unit_five'),
    path('generate-pdf-invoicing-report/', views.generate_pdf_invoicing_report, name='generate_pdf_invoicing_report'),


    path('comparative-reports/', views.reports_comparative_page, name='reports_comparative_page'),

    path('employees/', views.employees_page, name='employees_page'),
    path('create-employee', views.create_employee, name='create_employee'),
    path('edit-employee/', views.edit_employee, name='edit_employee'),
    path('delete-employees/', views.delete_employee, name='delete_employee'),
    path('get-employee/<int:employee_id>/', views.get_employee, name='get_employee'),

    path('options/', views.options_page, name='options_page'),
    path('create-option/', views.create_option, name='create_option'),
    path('get-option/<int:option_id>/', views.get_options, name='get_options'),
    path('edit-option/', views.edit_option, name='edit_option'),
    path('delete-options/', views.delete_option, name='delete_option'),
    
    path('shifts/', views.shifts_page, name='shifts_page'),
    path('create-shift/', views.create_shift, name='create_shift'),
    path('get-shift/<int:shift_id>/', views.get_shifts, name='get_shifts'),
    path('delete-shifts/', views.delete_shift, name='delete_shift'),
    path('edit-shifts/', views.edit_shift, name='edit_shift'),

    path('companies/', views.companies_page, name='companies_page'),
    path('create-company/', views.create_company, name='create_company'),
    path('get-company/<int:company_id>/', views.get_companies, name='get_companies'),
    path('delete-companies/', views.delete_company, name='delete_company'),
    path('edit-companies/', views.edit_company, name='edit_company'),

    path('units/', views.units_page, name='units_page'),
    path('create-unity/', views.create_unity, name='create_unity'),
    path('get-unity/<int:unity_id>/', views.get_units, name='get_units'),
    path('delete-units/', views.delete_unity, name='delete_unity'),
    path('edit-units/', views.edit_unity, name='edit_unity'),

    path('my-profile/', views.profile_page, name='profile_page'),
    path('change-password', views.change_password, name='change_password'),


    path('restaurants/', views.restaurant_page, name='restaurant_page'),
    path('create-restaurant/', views.create_restaurant, name='create_restaurant'),
    path('get-restaurant/<int:restaurant_id>/', views.get_restaurants, name='get_restaurants'),
    path('edit-restaurant/', views.edit_restaurant, name='edit_restaurant'),
    path('delete-restaurant/', views.delete_restaurant, name='delete_restaurant'),
]


if settings.DEBUG:  # Apenas no modo de desenvolvimento
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'menu.views.custom_404_view'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
]

menu/views.py
import json
from django.db.models import Count, Q
from django.shortcuts import render, redirect, get_object_or_404 
from .models import WeekMenu, Employee, Unity, PreviousUserChoice, Restaurant
from datetime import datetime
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login,logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .models import UserChoice, Options, Employee, Company, Shift, Profile, PreviousWeekMenu
import logging
from utils.menu.decorators import user_has_rh_profile, user_has_rh_and_restautant_profile
from utils.menu.report_functions import generate_full_report_function
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from collections import defaultdict
from utils.menu.helpers import convert_to_monday, is_the_date_in_seven_days
from utils.menu.report_pdf import generate_unity_options_pdf, generate_invoicing_report_pdf
from django.http import HttpResponse
import os
from django.contrib.auth import update_session_auth_hash
import locale

logger = logging.getLogger(__name__)
# Create your views here.


@login_required
def home(request):
    # Obter o cardápio semanal
    week_menus = WeekMenu.objects.prefetch_related('userchoice_set').all()
    user_choices = UserChoice.objects.filter(user=request.user)

    # Obter as escolhas do usuário
    user_choices_dict = {choice.menu.id: choice.option.id for choice in user_choices}


    return render(request, 'menu/pages/index.html', {
        'week_menus': week_menus,
        'week_menu': week_menus,
        'user_choices': user_choices_dict,
    })


def custom_404_view(request, exception):
    return render(request, 'menu/partials/_page_404.html', status=404)



@login_required
def last_week_menu(request):
    # Obter o cardápio semanal
    week_menus = PreviousWeekMenu.objects.all().order_by('date_meal')
    user_choices = PreviousUserChoice.objects.filter(user=request.user)

    # Criar um dicionário de escolhas do usuário
    user_choices_dict = {choice.menu.id: choice.option for choice in user_choices}

    user_choices_dict_plus = {choice.menu.id: choice.option.id for choice in user_choices}

    # Criar um resumo para cada dia
    resumo = []
    locale.setlocale(locale.LC_TIME, 'Portuguese_Brazil')
    for menu in week_menus:
        option = user_choices_dict.get(menu.id)
        if option:
            resumo.append({
                'day': menu.date_meal.strftime('%A').capitalize(),  # Nome do dia da semana
                'option': option.name_option,
            })
        else:
            resumo.append({
                'day': menu.date_meal.strftime('%A').capitalize(),
                'option': None,
            })

    return render(request, 'menu/pages/last_week_menu.html', {
        'week_menu': week_menus,
        'resumo': resumo,
        'user_choices': user_choices_dict_plus,
    })




@login_required
def progress_page(request):
    return render(request, 'menu/pages/page_progress.html')



def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Verifique se o nome de usuário e senha foram fornecidos
        if not username or not password:
            messages.error(request, 'Usuário ou senha incorretos!')
            return redirect('menu:login')

        user = authenticate(request, username=username, password=password)

        # Se não encontrar o usuário
        if not user:
            messages.error(request, 'Usuário ou senha incorretos!')
            return redirect('menu:login')

        # Fazer login do usuário
        auth_login(request, user)

        messages.success(request, 'Usuário logado com sucesso!')
        return redirect('menu:home')

    # Se o método não for POST, apenas renderize a página de login
    return render(request, 'menu/pages/login.html')



def logout(request):
    # Efetua o logout do usuário
    auth_logout(request)


    # Redireciona para a página de login
    return redirect('menu:login')


@login_required
def save_user_choices(request):
    if request.method == 'POST':
        logger.info(request.POST)

        # Aqui estamos assumindo que o campo será algo como 'choice_1', 'choice_2', etc.
        for key in request.POST:
            if key.startswith('choice_'):  # Para garantir que estamos pegando os campos corretos
                # Extrai o ID do menu (que é o dia da semana)
                menu_id = key.split('_')[1]  # Agora temos o id do menu (por exemplo, 1 para segunda-feira)
                option_id = request.POST.get(key)  # Pega o id da opção escolhida para esse dia

                if option_id and option_id != 'null':  # Se o option_id não for vazio ou nulo
                    try:
                        # Buscando a instância da opção para o dia específico
                        option_instance = Options.objects.get(id=option_id)
                    except Options.DoesNotExist:
                        option_instance = None  # Caso a opção não exista

                    if option_instance:
                        # Se a opção foi encontrada, cria ou atualiza a escolha
                        UserChoice.objects.update_or_create(
                            user=request.user,
                            menu_id=menu_id,  # Menu_id representando o dia correto
                            day_of_week=menu_id,  # Usa menu_id para distinguir entre os dias
                            defaults={'option': option_instance},
                        )
                    else:
                        # Se a opção não existe, podemos registrar um erro ou um valor padrão
                        logger.error(f"Option with ID {option_id} does not exist for day {menu_id}.")
                else:  # Se o option_id estiver vazio ou for 'null' (quando desmarcado)
                    # Deleta a escolha existente se o option_id não foi fornecido (desmarcado)
                    user_choice = UserChoice.objects.filter(
                        user=request.user,
                        menu_id=menu_id,  # Menu_id para o dia correto
                        day_of_week=menu_id
                    )
                    if user_choice.exists():
                        user_choice.delete()  # Deleta a escolha existente quando desmarcado

    return redirect('menu:home')


# EMPLOYEE PAGE FUNCTIONS

@login_required
@user_has_rh_profile  # Restringe o acesso a usuários com perfil RH
def employees_page(request):

# Obter filtros do GET
    search = request.GET.get('search', '')  # Nome do campo no formulário é "search"
    shift = request.GET.get('shift', '')  # Nome do campo no formulário é "shift"
    company = request.GET.get('company', '')  # Nome do campo no formulário é "company"
    unity = request.GET.get('unity', '')  # Nome do campo no formulário é "unity"
    
    # Querysets para filtros e colaboradores
    employees_company = Employee.objects.all()
    shifts_company = Shift.objects.all()
    companies = Company.objects.all()
    units = Unity.objects.all()
    profiles = Profile.objects.all()

    # Filtragem da lista de colaboradores
    employees_list = Employee.objects.all()

    if search:
        employees_list = employees_list.filter(first_name__icontains=search)
    if shift:
        employees_list = employees_list.filter(shift__shift=shift)  # Comparando com o nome do turno
    if company:
        employees_list = employees_list.filter(company__company_name=company)
    if unity:
        employees_list = employees_list.filter(unity__unity_name=unity)

    # Paginação
    paginator = Paginator(employees_list, 10)  # Exibe 10 colaboradores por página
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # Renderizar template com contexto
    return render(
        request,
        'menu/pages/employees.html',
        context={
            'employees_company': employees_company,
            'shifts_company': shifts_company,
            'companies': companies,
            'units': units,
            'page_obj': page_obj,
            'profiles': profiles,
            'request': request,  # Passa request para o template (opcional, para reutilizar filtros)
        }
    )


@login_required
@user_has_rh_profile  # Restringe o acesso a usuários com perfil RH
def create_employee(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        birth_date_str = request.POST.get('birth_date')  # Recebido como string
        shift_id = request.POST.get('shift')
        company_id = request.POST.get('company')
        unity_id = request.POST.get('unity')
        profile_id = request.POST.get('profile')
        vacation = request.POST.get('vacation') == 'on'
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        home_office = request.POST.get('home_office') == 'on'

        # Valida se todos os campos obrigatórios foram preenchidos
        if not all([first_name, last_name, birth_date_str, shift_id, company_id, unity_id, profile_id]):
            messages.error(request, "Todos os campos são obrigatórios.")
            return redirect('menu:employees_page')  # Ajuste para a URL correta

        try:
            # Converte a string para um objeto date
            birth_date = datetime.strptime(birth_date_str, '%Y-%m-%d').date()

            # Obtém os objetos relacionados de Turno, Empresa e Perfil
            shift = Shift.objects.get(id=shift_id)
            company = Company.objects.get(id=company_id)
            unity = Unity.objects.get(id=unity_id)
            profile = Profile.objects.get(id=profile_id)

            # Cria o objeto Employee
            employee = Employee.objects.create(
                first_name=first_name,

menu/templates/menu/partials/_footer.html
<footer class="d-flex align-items-center justify-content-between text-center mt-5 py-3 bg-success bg-opacity-75 text-white fw-bold">
    <!-- Imagem à esquerda -->
    <div class="footer-left">
        <img src="/media/global/sustenpratos_branco.png" alt="Logo branco" style="max-height: 110px;">
    </div>

    <!-- Conteúdo central -->
    <div class="footer-center">
        <p id="parag_foot">2024 ~ <script>document.write(new Date().getFullYear());</script></p>
        <p id="parag_foot">Desenvolvido por Kevin Neres</p>
    </div>

    <!-- (Opcional) Logos à direita -->
    <div class="footer-right">
        <img src="/media/global/logo_fulpel_branco.png" alt="Logo Fulpel" style="max-height: 55px;">
    </div> 
</footer>

menu/templates/menu/partials/_header.html
{% load static %}

<!-- Menu Suspenso -->
<nav class="navbar navbar-expand-lg navbar-light sticky-top bg-success bg-opacity-75">
    <div class="container-fluid">
        <a class="navbar-brand text-white fw-bold" href="{% url "menu:home" %}">
            <img src="/media/global/logo_branco_transparente.png" alt="Logo da Empresa" width="220" height="50">
        </a>
        <button class="navbar-toggler text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link text-white fw-bold" href="{% url "menu:home" %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white fw-bold" href="{% url "menu:progress_page" %}">Avaliações</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white fw-bold" href="{% url "menu:last_week_menu" %}">Cardápio anterior</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white fw-bold" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ request.user.employee.first_name }} {{ request.user.employee.last_name }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                        <li><a class="dropdown-item" href="{% url 'menu:profile_page' %}">Meu Perfil</a></li>
                        <li><a class="dropdown-item" href="{% url "menu:logout" %}">Sair</a>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

menu/templates/menu/partials/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

menu/templates/menu/partials/_modal_create_restaurant.html
<!-- Modal para criar colaborador -->
<div class="modal fade" id="createRestaurantModal" tabindex="-1" aria-labelledby="createRestaurantModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-success text-white">
                <h5 class="modal-title" id="createRestaurantModalLabel">Criar Restaurante</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" action="{% url 'menu:create_restaurant' %}">
                {% csrf_token %}
                <div class="modal-body">
                    <!-- Primeira linha -->
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="full_name" class="form-label">Restaurante</label>
                            <input type="text" id="full_name" name="full_name" class="form-control" required>
                        </div>
                        <div class="col-md-6">
                            <label for="short_name" class="form-label">Nome curto</label>
                            <input type="text" id="short_name" name="short_name" class="form-control" required>
                        </div>
                    </div>

                    <!-- Informação adicional -->
                    <p class="text-muted small mt-3">
                        Login e senha serão gerados automaticamente.  <br>
                        O login de acesso do restaurante é seu nome curto (ex. jeitinhobrasileiro) 
                        e a senha gerada é composta pelo nome curto + @ + ano de cadastro (jeitinhobrasileiro@2025)
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>

menu/templates/menu/partials/_modal_create_user.html
<!-- Modal para criar colaborador -->
<div class="modal fade" id="createEmployeeModal" tabindex="-1" aria-labelledby="createEmployeeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-success text-white">
                <h5 class="modal-title" id="createEmployeeModalLabel">Criar Colaborador</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" action="{% url 'menu:create_employee' %}">
                {% csrf_token %}
                <div class="modal-body">
                    <!-- Primeira linha -->
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="first_name" class="form-label">Nome</label>
                            <input type="text" id="first_name" name="first_name" class="form-control" required>
                        </div>
                        <div class="col-md-6">
                            <label for="last_name" class="form-label">Sobrenome</label>
                            <input type="text" id="last_name" name="last_name" class="form-control" required>
                        </div>
                    </div>
                    <!-- Segunda linha -->
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="shift" class="form-label">Turno</label>
                            <select id="shift" name="shift" class="form-select" required>
                                <option value="" selected disabled>Selecione um turno</option>
                                {% for shift in shifts_company %}
                                    <option value="{{ shift.id }}">{{ shift.shift }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-6">
                            <label for="company" class="form-label">Empresa</label>
                            <select id="company" name="company" class="form-select" required>
                                <option value="" selected disabled>Selecione uma empresa</option>
                                {% for company in companies %}
                                    <option value="{{ company.id }}">{{ company.company_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <!-- Terceira linha -->
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <label for="birth_date" class="form-label">Data de Nasc.</label>
                            <input type="date" id="birth_date" name="birth_date" class="form-control" required>
                        </div>
                        <div class="col-md-6">
                            <label for="unity" class="form-label">Unidade de refeição</label>
                            <select id="unity" name="unity" class="form-select" required>
                                <option value="" selected disabled>Selecione uma unidade</option>
                                {% for unity in  units %}
                                    <option value="{{ unity.id }}"> {{ unity.unity_name }} </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                     <!-- Quarta linha -->
                     <div class="row mb-3">
                            <label for="profile" class="form-label">Perfil</label>
                            <select id="profile" name="profile" class="form-select" required>
                                <option value="" selected disabled>Selecione um perfil</option>
                                {% for profile in  profiles %}
                                    <option value="{{ profile.id }}"> {{ profile.profile }} </option>
                                {% endfor %}
                            </select>
                    </div>

                    <div class="row mb-3">
                        <!-- Checkbox para Férias -->
                        <div class="col-auto">
                            <div class="form-check form-check-inline">
                                <input type="checkbox" id="vacation" name="vacation" class="form-check-input">
                                <label for="vacation" class="form-check-label">Férias?</label>
                            </div>
                        </div>
                    
                        <!-- Checkbox para Home Office -->
                        <div class="col-auto">
                            <div class="form-check form-check-inline">
                                <input type="checkbox" id="home_office" name="home_office" class="form-check-input">
                                <label for="home_office" class="form-check-label">Home Office?</label>
                            </div>
                        </div>
                    </div>
                    
                    <!-- Campos de data para Férias -->
                    <div id="vacation_dates" class="row mb-3" style="display: none;">
                        <div class="col-md-6">
                            <label for="start_date" class="form-label">Início das Férias</label>
                            <input type="date" id="start_date" name="start_date" class="form-control" disabled>
                        </div>
                        <div class="col-md-6">
                            <label for="end_date" class="form-label">Fim das Férias</label>
                            <input type="date" id="end_date" name="end_date" class="form-control" disabled>
                        </div>
                    </div>

                    <!-- Informação adicional -->
                    <p class="text-muted small mt-3">
                        Login e senha serão gerados automaticamente.  <br>
                        O login de acesso do colaborador é a junção de seu nome com seu primeiro sobrenome (ex. joaquimtorres) e a senha gerada são dia, mês e ano do nascimento (ex. 20092001).
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>



<script>
    document.getElementById('vacation').addEventListener('change', function () {
        const vacationDates = document.getElementById('vacation_dates');
        const startDate = document.getElementById('start_date');
        const endDate = document.getElementById('end_date');

        if (this.checked) {
            vacationDates.style.display = 'flex'; // Mostra os campos de data
            startDate.disabled = false; // Habilita o campo de data de início
            endDate.disabled = false; // Habilita o campo de data de fim
        } else {
            vacationDates.style.display = 'none'; // Oculta os campos de data
            startDate.disabled = true; // Desabilita o campo de data de início
            endDate.disabled = true; // Desabilita o campo de data de fim
        }
    });
</script>

menu/templates/menu/partials/_restaurant_header.html
{% load static %}

<!-- Menu Suspenso -->
 <div class="menu-admin-div">
    <nav class="navbar navbar-expand-lg navbar-light sticky-top bg-success bg-opacity-75">
        <div class="container-fluid">
            <a class="navbar-brand text-white fw-bold" href="{% url 'menu:home' %}">
                <img src="/media/global/logo_branco_transparente.png" alt="Logo da Empresa" width="220" height="50">
            </a>
            <button class="navbar-toggler text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white fw-bold" href="{% url 'menu:home' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white fw-bold" href="#" id="adminDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Admin
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="adminDropdown">
                            <li><a class="dropdown-item" href="{% url 'menu:weekly_menu' %}">Cardápio Semanal</a></li>
                            <li class="dropdown-submenu">
                                <a class="dropdown-item dropdown-toggle" href="#">Relatórios</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'menu:reports_page' %}">Entrega / Faturamento</a></li>
                                    <li><a class="dropdown-item" href="{% url 'menu:reports_comparative_page' %}">Comparativo Faturamento</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white fw-bold" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ request.user.restaurant.short_name }}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                            <li><a class="dropdown-item" href="{% url 'menu:profile_page' %}">Meu Perfil</a></li>
                            <li><a class="dropdown-item" href="{% url "menu:logout" %}">Sair</a>
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        // Controla a abertura e fechamento do submenu "Relatórios"
        document.querySelectorAll('.dropdown-submenu > a').forEach(function (submenuToggle) {
            submenuToggle.addEventListener('click', function (e) {
                e.preventDefault(); // Evita o comportamento padrão do link
                e.stopPropagation(); // Impede que o clique feche o menu principal

                const submenu = this.nextElementSibling;

                // Alterna a exibição do submenu
                if (submenu.classList.contains('show')) {
                    submenu.classList.remove('show');
                } else {
                    // Fecha outros submenus abertos
                    document.querySelectorAll('.dropdown-menu.show').forEach(function (menu) {
                        menu.classList.remove('show');
                    });
                    submenu.classList.add('show');
                }
            });
        });

        // Controla o comportamento ao clicar fora do menu
        document.addEventListener('click', function (e) {
            if (!e.target.closest('.dropdown')) {
                // Fecha todos os menus e submenus
                document.querySelectorAll('.dropdown-menu.show').forEach(function (menu) {
                    menu.classList.remove('show');
                });
            }
        });

        // Garante que o menu principal "Admin" não feche automaticamente
        document.querySelectorAll('.dropdown > a').forEach(function (menuToggle) {
            menuToggle.addEventListener('click', function (e) {
                e.stopPropagation(); // Impede que o clique no menu principal feche outros menus
            });
        });
    });
</script>