menu/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'menu'

urlpatterns = [
    path('', views.home, name='home'),
    path('last-week-menu', views.last_week_menu, name='last_week_menu'),
    path('page-in-progress', views.progress_page, name='progress_page'),
    path('weekly-menu/', views.weekly_menu, name='weekly_menu'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'), 
    path('save-user-choices', views.save_user_choices, name='save_user_choices'),
    
    path('update-weekly-menu', views.update_weekly_menu, name='update_weekly_menu'),
    
    path('reports/', views.reports_page, name='reports_page'),
    path('generate-full-report/', views.generate_full_report_button, name='generate_full_report_button'),
    path('generate-pdf-report-unity-one/', views.generate_pdf_report_unit_one, name='generate_pdf_report_unit_one'),
    path('generate-pdf-report-unity-two/', views.generate_pdf_report_unit_two, name='generate_pdf_report_unit_two'),
    path('generate-pdf-report-unity-five/', views.generate_pdf_report_unit_five, name='generate_pdf_report_unit_five'),
    path('generate-pdf-invoicing-report/', views.generate_pdf_invoicing_report, name='generate_pdf_invoicing_report'),


    path('comparative-reports/', views.reports_comparative_page, name='reports_comparative_page'),

    path('employees/', views.employees_page, name='employees_page'),
    path('create-employee', views.create_employee, name='create_employee'),
    path('edit-employee/', views.edit_employee, name='edit_employee'),
    path('delete-employees/', views.delete_employee, name='delete_employee'),
    path('get-employee/<int:employee_id>/', views.get_employee, name='get_employee'),

    path('options/', views.options_page, name='options_page'),
    path('create-option/', views.create_option, name='create_option'),
    path('get-option/<int:option_id>/', views.get_options, name='get_options'),
    path('edit-option/', views.edit_option, name='edit_option'),
    path('delete-options/', views.delete_option, name='delete_option'),
    
    path('shifts/', views.shifts_page, name='shifts_page'),
    path('create-shift/', views.create_shift, name='create_shift'),
    path('get-shift/<int:shift_id>/', views.get_shifts, name='get_shifts'),
    path('delete-shifts/', views.delete_shift, name='delete_shift'),
    path('edit-shifts/', views.edit_shift, name='edit_shift'),

    path('companies/', views.companies_page, name='companies_page'),
    path('create-company/', views.create_company, name='create_company'),
    path('get-company/<int:company_id>/', views.get_companies, name='get_companies'),
    path('delete-companies/', views.delete_company, name='delete_company'),
    path('edit-companies/', views.edit_company, name='edit_company'),

    path('units/', views.units_page, name='units_page'),
    path('create-unity/', views.create_unity, name='create_unity'),
    path('get-unity/<int:unity_id>/', views.get_units, name='get_units'),
    path('delete-units/', views.delete_unity, name='delete_unity'),
    path('edit-units/', views.edit_unity, name='edit_unity'),

    path('my-profile/', views.profile_page, name='profile_page'),
    path('change-password', views.change_password, name='change_password'),


    path('restaurants/', views.restaurant_page, name='restaurant_page'),
    path('create-restaurant/', views.create_restaurant, name='create_restaurant'),
    path('get-restaurant/<int:restaurant_id>/', views.get_restaurants, name='get_restaurants'),
    path('edit-restaurant/', views.edit_restaurant, name='edit_restaurant'),
    path('delete-restaurant/', views.delete_restaurant, name='delete_restaurant'),
]


if settings.DEBUG:  # Apenas no modo de desenvolvimento
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'menu.views.custom_404_view'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
]

menu/views.py
import json
from django.db.models import Count, Q
from django.shortcuts import render, redirect, get_object_or_404 
from .models import WeekMenu, Employee, Unity, PreviousUserChoice, Restaurant
from datetime import datetime
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login,logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .models import UserChoice, Options, Employee, Company, Shift, Profile, PreviousWeekMenu
import logging
from utils.menu.decorators import user_has_rh_profile, user_has_rh_and_restautant_profile
from utils.menu.report_functions import generate_full_report_function
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from collections import defaultdict
from utils.menu.helpers import convert_to_monday, is_the_date_in_seven_days
from utils.menu.report_pdf import generate_unity_options_pdf, generate_invoicing_report_pdf
from django.http import HttpResponse
import os
from django.contrib.auth import update_session_auth_hash
import locale

logger = logging.getLogger(__name__)
# Create your views here.


@login_required
def home(request):
    # Obter o cardápio semanal
    week_menus = WeekMenu.objects.prefetch_related('userchoice_set').all()
    user_choices = UserChoice.objects.filter(user=request.user)

    # Obter as escolhas do usuário
    user_choices_dict = {choice.menu.id: choice.option.id for choice in user_choices}


    return render(request, 'menu/pages/index.html', {
        'week_menus': week_menus,
        'week_menu': week_menus,
        'user_choices': user_choices_dict,
    })


def custom_404_view(request, exception):
    return render(request, 'menu/partials/_page_404.html', status=404)



@login_required
def last_week_menu(request):
    # Obter o cardápio semanal
    week_menus = PreviousWeekMenu.objects.all().order_by('date_meal')
    user_choices = PreviousUserChoice.objects.filter(user=request.user)

    # Criar um dicionário de escolhas do usuário
    user_choices_dict = {choice.menu.id: choice.option for choice in user_choices}

    user_choices_dict_plus = {choice.menu.id: choice.option.id for choice in user_choices}

    # Criar um resumo para cada dia
    resumo = []
    locale.setlocale(locale.LC_TIME, 'Portuguese_Brazil')
    for menu in week_menus:
        option = user_choices_dict.get(menu.id)
        if option:
            resumo.append({
                'day': menu.date_meal.strftime('%A').capitalize(),  # Nome do dia da semana
                'option': option.name_option,
            })
        else:
            resumo.append({
                'day': menu.date_meal.strftime('%A').capitalize(),
                'option': None,
            })

    return render(request, 'menu/pages/last_week_menu.html', {
        'week_menu': week_menus,
        'resumo': resumo,
        'user_choices': user_choices_dict_plus,
    })




@login_required
def progress_page(request):
    return render(request, 'menu/pages/page_progress.html')



def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Verifique se o nome de usuário e senha foram fornecidos
        if not username or not password:
            messages.error(request, 'Usuário ou senha incorretos!')
            return redirect('menu:login')

        user = authenticate(request, username=username, password=password)

        # Se não encontrar o usuário
        if not user:
            messages.error(request, 'Usuário ou senha incorretos!')
            return redirect('menu:login')

        # Fazer login do usuário
        auth_login(request, user)

        messages.success(request, 'Usuário logado com sucesso!')
        return redirect('menu:home')

    # Se o método não for POST, apenas renderize a página de login
    return render(request, 'menu/pages/login.html')



def logout(request):
    # Efetua o logout do usuário
    auth_logout(request)


    # Redireciona para a página de login
    return redirect('menu:login')


@login_required
def save_user_choices(request):
    if request.method == 'POST':
        logger.info(request.POST)

        # Aqui estamos assumindo que o campo será algo como 'choice_1', 'choice_2', etc.
        for key in request.POST:
            if key.startswith('choice_'):  # Para garantir que estamos pegando os campos corretos
                # Extrai o ID do menu (que é o dia da semana)
                menu_id = key.split('_')[1]  # Agora temos o id do menu (por exemplo, 1 para segunda-feira)
                option_id = request.POST.get(key)  # Pega o id da opção escolhida para esse dia

                if option_id and option_id != 'null':  # Se o option_id não for vazio ou nulo
                    try:
                        # Buscando a instância da opção para o dia específico
                        option_instance = Options.objects.get(id=option_id)
                    except Options.DoesNotExist:
                        option_instance = None  # Caso a opção não exista

                    if option_instance:
                        # Se a opção foi encontrada, cria ou atualiza a escolha
                        UserChoice.objects.update_or_create(
                            user=request.user,
                            menu_id=menu_id,  # Menu_id representando o dia correto
                            day_of_week=menu_id,  # Usa menu_id para distinguir entre os dias
                            defaults={'option': option_instance},
                        )
                    else:
                        # Se a opção não existe, podemos registrar um erro ou um valor padrão
                        logger.error(f"Option with ID {option_id} does not exist for day {menu_id}.")
                else:  # Se o option_id estiver vazio ou for 'null' (quando desmarcado)
                    # Deleta a escolha existente se o option_id não foi fornecido (desmarcado)
                    user_choice = UserChoice.objects.filter(
                        user=request.user,
                        menu_id=menu_id,  # Menu_id para o dia correto
                        day_of_week=menu_id
                    )
                    if user_choice.exists():
                        user_choice.delete()  # Deleta a escolha existente quando desmarcado

    return redirect('menu:home')


# EMPLOYEE PAGE FUNCTIONS

@login_required
@user_has_rh_profile  # Restringe o acesso a usuários com perfil RH
def employees_page(request):

# Obter filtros do GET
    search = request.GET.get('search', '')  # Nome do campo no formulário é "search"
    shift = request.GET.get('shift', '')  # Nome do campo no formulário é "shift"
    company = request.GET.get('company', '')  # Nome do campo no formulário é "company"
    unity = request.GET.get('unity', '')  # Nome do campo no formulário é "unity"
    
    # Querysets para filtros e colaboradores
    employees_company = Employee.objects.all()
    shifts_company = Shift.objects.all()
    companies = Company.objects.all()
    units = Unity.objects.all()
    profiles = Profile.objects.all()

    # Filtragem da lista de colaboradores
    employees_list = Employee.objects.all()

    if search:
        employees_list = employees_list.filter(first_name__icontains=search)
    if shift:
        employees_list = employees_list.filter(shift__shift=shift)  # Comparando com o nome do turno
    if company:
        employees_list = employees_list.filter(company__company_name=company)
    if unity:
        employees_list = employees_list.filter(unity__unity_name=unity)

    # Paginação
    paginator = Paginator(employees_list, 10)  # Exibe 10 colaboradores por página
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # Renderizar template com contexto
    return render(
        request,
        'menu/pages/employees.html',
        context={
            'employees_company': employees_company,
            'shifts_company': shifts_company,
            'companies': companies,
            'units': units,
            'page_obj': page_obj,
            'profiles': profiles,
            'request': request,  # Passa request para o template (opcional, para reutilizar filtros)
        }
    )


@login_required
@user_has_rh_profile  # Restringe o acesso a usuários com perfil RH
def create_employee(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        birth_date_str = request.POST.get('birth_date')  # Recebido como string
        shift_id = request.POST.get('shift')
        company_id = request.POST.get('company')
        unity_id = request.POST.get('unity')
        profile_id = request.POST.get('profile')
        vacation = request.POST.get('vacation') == 'on'
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        home_office = request.POST.get('home_office') == 'on'

        # Valida se todos os campos obrigatórios foram preenchidos
        if not all([first_name, last_name, birth_date_str, shift_id, company_id, unity_id, profile_id]):
            messages.error(request, "Todos os campos são obrigatórios.")
            return redirect('menu:employees_page')  # Ajuste para a URL correta

        try:
            # Converte a string para um objeto date
            birth_date = datetime.strptime(birth_date_str, '%Y-%m-%d').date()

            # Obtém os objetos relacionados de Turno, Empresa e Perfil
            shift = Shift.objects.get(id=shift_id)
            company = Company.objects.get(id=company_id)
            unity = Unity.objects.get(id=unity_id)
            profile = Profile.objects.get(id=profile_id)

            # Cria o objeto Employee
            employee = Employee.objects.create(
                first_name=first_name,

menu/templates/menu/pages/comparative_report.html
{% extends "global/base.html" %}
{% load menu_filters %}

{% block title %}Relatório Comparativo Faturamento{% endblock title %}



{% block content %}
    <!-- Título Principal -->
    <div class="text-center my-3">
        <h1 id="titulo_home" class="text-success-75">Relatório Comparativo Faturamento</i></h1>
        <p>Correspondente ao período {{ weekly_menu.0.date_meal|date:"d/m" }}  à {{ weekly_menu.4.date_meal|date:"d/m" }}</p>

        <h3>Quantidade de refeições solicitadas</h3>
        <table class="table table-bordered mt-3">
            <thead>
                <tr>
                    <th>Fechamento</th>
                    <th>Qt. colaboradores</th>
                </tr>
            </thead>
            <tbody>
                {% for company, data in company_data.items %}
                    <tr>
                        <td>{{ company }}</td>
                        <td>{{ data.employees_no_vacation_total }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <h3 class="text-center my-3" >FATURAMENTO (ENTREGA) {{ weekly_menu.0.date_meal|date:"d.m.Y" }} A {{ weekly_menu.4.date_meal|date:"d.m.Y" }}</h3>
        <table class="table table-bordered mt-3">
            <thead>
                <tr>
                    <th>Unidade</th>
                    <th></th>
                    <th>Qt. colaboradores</th>
                </tr>
            </thead>
            <tbody>
                {% for unit, total in employees_by_unit.items %}     
                    <tr>
                        <td> {{ unit }} </td>
                        <td>ALMOÇO (CUBA)</td>
                        <td> {{ total }} </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="mt-4">
            <label class="form-label fw-bold"> <h4> Total </h4> </label>
            <div><span class="fw-bold"> <h4> {{ total_employees_by_unit }} </h4> </span></div>
        </div>
        
        <div class="mt-5">
            <button class="btn btn-success">Gerar relatório comparativo</button>
        </div>
        
    </div>



{% endblock content %}

menu/templates/menu/pages/last_week_menu.html
{% extends "global/base.html" %}
{% load menu_filters %}

{% block title %}Cardápio Anterior{% endblock title %}



{% block content %}
    <!-- Título Principal -->
    <div class="text-center my-3">
        <h1 id="titulo_home" class="text-success-75">Cardápio Anterior</h1>
        <p id="p_home">Confira o cardápio da semana atual.</p>
        <p id="p_home">Cardápio {{ week_menu.0.date_meal|date:"d/m" }} à {{ week_menu.4.date_meal|date:"d/m" }}</p>
    </div>




    <input type="hidden" name="menu_id" value="{{ menu.id }}"> 
    <!-- Grid de Cards -->
    <div class="container">
        <div class="row row-cols-1 row-cols-md-5 g-4">
            <!-- Card 1 (Segunda) -->
            <div class="col">
                <div class="card h-100">
                    <img src="{{ week_menu.0.image_meal.url }}" class="card-img-top" alt="Imagem do card">
                    <div class="card-body" id="card_segunda">
                        <p class="text-left"> {{ week_menu.0.date_meal }} </p>
                        <h6 class="card-title text-left">Segunda-feira</h6>
                        <h5 class="text-left fw-bold"> {{ week_menu.0.title}} </h5>
                        <p class="text-left"> Com {{ week_menu.0.side_dish }} </p>
                        <div class="d-flex flex-column align-items-start">
                            <div class="d-flex flex-column align-items-start">
                                <input 
                                            type="hidden" 
                                            name="choice_{{ week_menu.0.id }}" 
                                            value="null"
                                        >
                                {% for option in week_menu.0.options.all %}
                                    <div class="form-check form-check-inline">
                                        <input 
                                            class="form-check-input" 
                                            type="radio" 
                                            name="choice_{{ week_menu.0.id }}" 
                                            value="{{ option.id }}" 
                                            id="option{{ week_menu.0.id }}_{{ forloop.counter }}"
                                            {% if user_choices|get_option:week_menu.0.id == option.id %}checked{% endif %}
                                            disabled = true
                                        >
                                        <label class="form-check-label" for="option{{ week_menu.0.id }}_{{ forloop.counter }}">{{ option.name_option }}</label>
                                    </div>
                                {% endfor %}
                            </div>
    
                        </div>
                    </div>
                    <div class="card-footer text-end">
                        <a href="{% url 'menu:progress_page' %}" class="btn btn-secondary btn-sm">?</a>
                    </div>
                </div>
            </div>

            

            <!-- Card 2 (Terça) -->
            <div class="col">
                <div class="card h-100">
                    <img src="{{ week_menu.1.image_meal.url }}"  class="card-img-top" alt="Imagem do card">
                    <div class="card-body text-white" id="card_terca">
                        <p class="text-left"> {{ week_menu.1.date_meal }} </p>
                        <h6 class="card-title text-left">Terça-feira</h6>
                        <h5 class="text-left fw-bold">{{ week_menu.1.title }}</h5>
                        <p class="text-left">Com {{ week_menu.1.side_dish }}</p>
                        <div class="d-flex flex-column align-items-start">
                            <input 
                                        type="hidden" 
                                        name="choice_{{ week_menu.1.id }}" 
                                        value="null"
                                    >
                            {% for option in week_menu.1.options.all %}
                                <div class="form-check form-check-inline">
                                    <input 
                                        class="form-check-input" 
                                        type="radio" 
                                        name="choice_{{ week_menu.1.id }}" 
                                        value="{{ option.id }}" 
                                        id="option{{ week_menu.1.id }}_{{ forloop.counter }}"
                                        {% if user_choices|get_option:week_menu.1.id == option.id %}checked{% endif %}
                                        disabled = true
                                    >
                                    <label class="form-check-label" for="option{{ week_menu.1.id }}_{{ forloop.counter }}">{{ option.name_option }}</label>
                                </div>
                            {% endfor %}
                        </div>

                    </div>
                    <div class="card-footer text-end">
                        <a href="{% url 'menu:progress_page' %}" class="btn btn-secondary btn-sm">?</a>
                    </div>
                </div>
            </div>


            <!-- Card 3 (Quarta) -->
            <div class="col">
                <div class="card h-100">
                    <img src="{{ week_menu.2.image_meal.url }}"  class="card-img-top" alt="Imagem do card">
                    <div class="card-body" id="card_quarta">
                        <p class="text-left"> {{ week_menu.2.date_meal }} </p>
                        <h6 class="card-title text-left">Quarta-feira</h6>
                        <h5 class="text-left fw-bold"> {{ week_menu.2.title }} </h5>
                        <p class="text-left">Com  {{ week_menu.2.side_dish }} </p>
                        <div class="d-flex flex-column align-items-start">
                            <input 
                                        type="hidden" 
                                        name="choice_{{ week_menu.2.id }}" 
                                        value="null"
                                    >
                            {% for option in week_menu.2.options.all %}
                                <div class="form-check form-check-inline">
                                    <input 
                                        class="form-check-input" 
                                        type="radio" 
                                        name="choice_{{ week_menu.2.id }}" 
                                        value="{{ option.id }}" 
                                        id="option{{ week_menu.2.id }}_{{ forloop.counter }}"
                                        {% if user_choices|get_option:week_menu.2.id == option.id %}checked{% endif %}
                                        disabled = true
                                    >
                                    <label class="form-check-label" for="option{{ week_menu.2.id }}_{{ forloop.counter }}">{{ option.name_option }}</label>
                                </div>
                            {% endfor %}
                        </div>

                    </div>
                    <div class="card-footer text-end">
                        <a href="{% url 'menu:progress_page' %}" class="btn btn-secondary btn-sm">?</a>
                    </div>
                </div>
            </div>


            <!-- Card 1 (Quinta) -->
            <div class="col">
                <div class="card h-100">
                    <img src="{{ week_menu.3.image_meal.url }}"  class="card-img-top" alt="Imagem do card">
                    <div class="card-body text-white" id="card_quinta">
                        <p class="text-left"> {{ week_menu.3.date_meal }}  </p>
                        <h6 class="card-title text-left">Quinta-feira</h6>
                        <h5 class="text-left fw-bold"> {{ week_menu.3.title}} </h5>
                        <p class="text-left">Com {{ week_menu.3.side_dish}} </p>
                        <div class="d-flex flex-column align-items-start">
                            <input 
                                        type="hidden" 
                                        name="choice_{{ week_menu.3.id }}" 
                                        value="null"
                                    >
                            {% for option in week_menu.3.options.all %}
                                <div class="form-check form-check-inline">
                                    <input 
                                        class="form-check-input" 
                                        type="radio" 
                                        name="choice_{{ week_menu.3.id }}" 
                                        value="{{ option.id }}" 
                                        id="option{{ week_menu.3.id }}_{{ forloop.counter }}"
                                        {% if user_choices|get_option:week_menu.3.id == option.id %}checked{% endif %}
                                        disabled = true
                                    >
                                    <label class="form-check-label" for="option{{ week_menu.3.id }}_{{ forloop.counter }}">{{ option.name_option }}</label>
                                </div>
                            {% endfor %}
                        </div>

                    </div>
                    <div class="card-footer text-end">
                        <a href="{% url 'menu:progress_page' %}" class="btn btn-secondary btn-sm">?</a>
                    </div>
                </div>
            </div>



            <!-- Card 1 (Sexta) -->
            <div class="col">
                <div class="card h-100">
                    <img src="{{ week_menu.4.image_meal.url }}"  class="card-img-top" alt="Imagem do card">
                    <div class="card-body" id="card_sexta">
                        <p class="text-left"> {{ week_menu.4.date_meal }}  </p>
                        <h6 class="card-title text-left">Sexta-feira</h6>
                        <h5 class="text-left fw-bold"> {{ week_menu.4.title}} </h5>
                        <p class="text-left">Com {{ week_menu.4.side_dish}} </p>
                        <div class="d-flex flex-column align-items-start">
                            <input 
                                        type="hidden" 
                                        name="choice_{{ week_menu.4.id }}" 
                                        value="null"
                                    >
                            {% for option in week_menu.4.options.all %}
                                <div class="form-check form-check-inline">
                                    <input 
                                        class="form-check-input" 
                                        type="radio" 
                                        name="choice_{{ week_menu.4.id }}" 
                                        value="{{ option.id }}" 
                                        id="option{{ week_menu.4.id }}_{{ forloop.counter }}"
                                        {% if user_choices|get_option:week_menu.4.id == option.id %}checked{% endif %}
                                        disabled = true
                                    >
                                    <label class="form-check-label" for="option{{ week_menu.4.id }}_{{ forloop.counter }}">{{ option.name_option }}</label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="card-footer text-end">
                        <a href="{% url 'menu:progress_page' %}" class="btn btn-secondary btn-sm">?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Resumo -->
    <div class="container mt-5">
        <h2>Resumo:</h2>
        <ul id="resumo-lista" class="list-group">
            {% for dia in resumo %}
                <li class="list-group-item">
                    {{ dia.day }}: 
                    {% if dia.option %}
                        Você pediu a opção "{{ dia.option }}"
                    {% else %}
                        Você não pediu opção
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>


{% endblock content %}

menu/templates/menu/pages/reports.html
{% extends "global/base.html" %}
{% load menu_filters %}

{% block title %}Relatório Faturamento{% endblock title %}



{% block content %}
    <!-- Título Principal -->
    <div class="text-center my-3">
        <h1 id="titulo_home" class="text-success-75">Relatório Faturamento</i></h1>
        <p>Correspondente ao período {{ weekly_menu.0.date_meal|date:"d/m" }}  à {{ weekly_menu.4.date_meal|date:"d/m" }}</p>

        <h3>FATURAMENTO {{ weekly_menu.0.date_meal|date:"d.m.Y" }} A {{ weekly_menu.4.date_meal|date:"d.m.Y" }}</h3>
        <table class="table table-bordered mt-3">
            <thead>
                <tr>
                    <th>Empresa</th>
                    <th>Qt. colaboradores </th>
                </tr>
            </thead>
            <tbody>
                {% for company, data in company_data.items %}
                    <tr>
                        <td>{{ company }}</td>
                        <td>{{ data.employees_no_vacation_total }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <h3 class="text-center my-3" >FATURAMENTO (ENTREGA) {{ weekly_menu.0.date_meal|date:"d.m.Y" }} A {{ weekly_menu.4.date_meal|date:"d.m.Y" }}</h3>
        <table class="table table-bordered mt-3">
            <thead>
                <tr>
                    <th>Unidade</th>
                    <th></th>
                    <th>Qt. colaboradores</th>
                </tr>
            </thead>
            <tbody>
                {% for unit, total in employees_by_unit.items %}     
                    <tr>
                        <td> {{ unit }} </td>
                        <td>ALMOÇO (CUBA)</td>
                        <td> {{ total }} </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="mt-4">
            <label class="form-label fw-bold"> <h4> Total </h4> </label>
            <div><span class="fw-bold"> <h4> {{ total_employees_by_unit }} </h4> </span></div>
        </div>

        <div class="mt-4">
            <!-- Botão mais largo para "Gerar relatório completo" -->
            <a href="{% url 'menu:generate_full_report_button' %}" class="btn btn-success w-75">
                Gerar relatório completo
            </a>
        </div>
        
        <div class="mt-2 d-flex justify-content-between w-75 mx-auto">
            <!-- Três botões com a mesma largura de 75% -->
            <a href="{% url 'menu:generate_pdf_report_unit_one' %}" class="btn btn-success w-100 mx-1">
                Gerar PDF Unidade 1
            </a>
            <a href="{% url 'menu:generate_pdf_report_unit_two' %}" class="btn btn-success w-100 mx-1">
                Gerar PDF Unidade 2
            </a>
            <a href="{% url 'menu:generate_pdf_report_unit_five' %}" class="btn btn-success w-100 mx-1">
                Gerar PDF Unidade 5
            </a>
        </div>
        
    </div>



{% endblock content %}